### PR TITLE
Changed amount to number.

### PR DESCRIPTION
**Pull request by Roald87**
See also #39, #122.

### CODE REVIEW

**Comment by sagatowski** [comment]
Thanks @Roald87! I cant't remember whether this result-string (`MsgFmtStr := 'Tests failed because the amount of tests (%s'`) is used anywhere in the TcUnit-Runner (probably not), but I think it needs to be checked. Also, same applies to the TcUnit-Verifier (check that the verifier does not check for exactly this string somewhere... which I think it might actually do!)

**Comment by Roald87** [comment]
Forgot to commit one change. The project builds now and I ran TcUnit-Verifier and all tests pass.

**Comment by sagatowski** [comment]
Do you know if this is used anywhere in the TcUnit-Runner?

**Comment by Roald87** [comment]
```bash
 $ grep -ri "amount" *

TcUnit-Runner/Program.cs: 
log.Error("ERROR: The amount of tasks is not equal to 1 (one). Found " + realTimeTasksTreeItem.ChildCount.ToString() + " amount of tasks. Please provide which task is the TcUnit task");

TcUnit-Runner/TcUnitResultCollector.cs:
log.Error("ERROR: While parsing TcUnit results, got test case number " + currentTestCaseInTestSuiteNumber + " but expected amount is " + testSuiteNumberOfTests);
```

These are only for logging purposes. I guess not critical? I can also change amount here to number if you'd like.

**Comment by sagatowski** [comment]
> ```shell
>  $ grep -ri "amount" *
> 
> TcUnit-Runner/Program.cs: 
> log.Error("ERROR: The amount of tasks is not equal to 1 (one). Found " + realTimeTasksTreeItem.ChildCount.ToString() + " amount of tasks. Please provide which task is the TcUnit task");
> 
> TcUnit-Runner/TcUnitResultCollector.cs:
> log.Error("ERROR: While parsing TcUnit results, got test case number " + currentTestCaseInTestSuiteNumber + " but expected amount is " + testSuiteNumberOfTests);
> ```
> 
> These are only for logging purposes. I guess not critical? I can also change amount here to number if you'd like.

Thanks for checking. Yes, do a PR there too please!

**Comment by Roald87** [comment]
See https://github.com/tcunit/TcUnit-Runner/pull/20

**Comment by sagatowski** [comment]
Merged.
Thanks @Roald87! 

Result:
```
2021-03-05 21:57:19 - Starting TcUnit-Verifier...
2021-03-05 21:57:19 - In Visual Studio solution file, found visual studio version 12.0
2021-03-05 21:57:19 - Loading the Visual Studio Development Tools Environment (DTE)...
2021-03-05 21:57:30 - Cleaning and building TcUnit-Verifier_TwinCAT solution...
2021-03-05 21:57:30 - Generating TcUnit-Verifier_TwinCAT boot project...
2021-03-05 21:57:46 - Activating TcUnit-Verifier_TwinCAT configuration...
2021-03-05 21:57:51 - Restarting TwinCAT...
2021-03-05 21:57:51 - Waiting for TcUnit-Verifier_TwinCAT to finish running tests...
2021-03-05 21:58:01 - ... got 154 report lines so far.
2021-03-05 21:58:11 - ... got 680 report lines so far.
2021-03-05 21:58:22 - ... got 1230 report lines so far.
2021-03-05 21:58:33 - ... got 1371 report lines so far.
2021-03-05 21:58:35 - Asserting results...
2021-03-05 21:58:35 - Done.
2021-03-05 21:58:35 - Closing the Visual Studio Development Tools Environment (DTE), please wait...
2021-03-05 21:58:58 - Exiting application...
```

**Pull request merged**
