### PR TITLE
Refactored FindVisualStudioVersion() method.

### PR DESCRIPTION
**Pull request by Roald87**
I rewrote the method for my _TcBlack_ project, so you might like it as well. I think this version is a bit shorter and clearer, especially if you know some Regex.

### CODE REVIEW

**Comment by sagatowski** [comment]
Yes, this is great! I always disliked that method and thought that regular expressions would be a perfect fit! I will test this during the weekend, and merge it afterwards! Thanks @Roald87 !

**Comment by sagatowski** [comment]
Any reason this was deleted/closed?

**Comment by Roald87** [comment]
Sorry, I was cleaning up some branches and didn't realize that it would also be deleted here. Now it should be ok again I think?

**Comment by sagatowski** [comment]
All fine now :)

**Comment by sagatowski** [comment]
This has been merged into main. Thanks for the contribution @Roald87 !

**Pull request merged**
