### PR TITLE
Replaced GVL_Constants_TcUnit with GVL_Param_TcUnit.

### PR DESCRIPTION
**Pull request by Aliazzzz**
Slight adjustment in TEST_FINISHED.

### CODE REVIEW

**Comment by sagatowski** [comment]
Have you verified that you still get the same results with the TcUnit-Verifier?

**Comment by Aliazzzz** [comment]
Hi,

Sorry,
I have forgotten this as I had a fight with the GIT Commit/push mechanism.
Also note that new commit equals 0.9.0.0(!) as I wanted to let it up to your own disgression to set a new version (e.g. v0.9.0.1)

Allthough I am very confident it will PASS, I have run the verifier.

  *   Succes! (see below)
[cid:image001.gif@01D534D1.1726B6C0]

**Comment by Aliazzzz** [comment]
Hi,

In case you have missed it,  TcUnit-Verifier =>Succes!

**Comment by sagatowski** [comment]
That's fantastic! I'll do the merge in the weekend.
Thanks!

**Comment by Aliazzzz** [comment]
Have you seen some open-source xmwriter in IEC somewhere? Ideally this would be super.
I have searched the web, but not much luck so far… If we find such a code, we can have a headstart.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Jakob Sagatowski <notifications@github.com>
Verzonden: Tuesday, July 9, 2019 6:18:20 PM
Aan: tcunit/TcUnit
CC: Aliazzzz; Author
Onderwerp: Re: [tcunit/TcUnit] Replaced GVL_Constants_TcUnit with GVL_Param_TcUnit. (#34)


That's fantastic! I'll do the merge in the weekend.
Thanks!

**Comment by sagatowski** [comment]
I've tried to merge, but it seems you've forgot to commit the GVL_Param_TcUnit. It's missing:
https://github.com/Aliazzzz/TcUnit/tree/master/TcUnit/TcUnit/GVLs

**Comment by sagatowski** [comment]
Merged in commit b035414.
Thanks for your contribution!

**Pull request merged**
