### PR TITLE
junitxmlpublisher fix

### PR DESCRIPTION
**Pull request by Aliazzzz**
Quick fixes to enable the xml writer output => now **works**

### CODE REVIEW

**Comment by sagatowski** [comment]
First of all, sorry for the long delay of the review of the PR.
Here are my initial comments:

1. Firstly, it's not necessary to create another PR everytime you do a re-commit. You can re-use the existing PR.
2. Please squash commits.
3. Remove all unused comments (for example: //{attribute 'hide_all_locals'} and //Test_Prepend();)
4. Remove all disabled code
5. CfUnitTestResults?
6. I don't think it's necesarry to create a separate Param for XmlControl. Put the variables in params for TcUnit, although separate them clearly.
7. The reports are named JUnit all over the code. JUnit is an unit testing framework for Java. It can produce reports in xUnit format (just as many other unit testing frameworks), which is the correct name for the reports. In other words, rename all instances of jUnit to xUnit.
8. MaxFileSize : UDINT := 65535; What is the maximum size? Maybe a comment about this?
9. Set the EnablePublish parameter to false default (in 1.1 it will be TcUnit-Runner used default)
10. Settings for the "Real-Time" have been changed in the TcUnit-Verifier (see TcUnit-Verifier_TwinCAT.tsproj), this inhibits the tests on all systems. Leave them at default.
11. Same as above for TcUnit (see TcUnit/TcUnit.tsproj). Leave this file unchanged.
12. There are no tests added in the C#/.net verifier. By running the .NET-verifier, how can I know that the xUnit publishing works? I see there are two test FBs (FB_TestStreamBuffer and FB_TestFileControl) added in the test-suites for TwinCAT-verifier, but I don't see any C#-classes added for these two. Maybe you forgot to commit some C# code? With the code today I can make changes in the FB_StreamBuffer or file control, and the .NET-verifier will still say everything is OK.
13. In TcUnitVerifier.plcproj I noticed the addition:
  <ItemGroup>
    <SubObject Include="FB_TestStreamBuffer.Test_Prepend">
      <ExcludeFromBuild>true</ExcludeFromBuild>
    </SubObject>
  </ItemGroup>
  
  Whats this?
14. The test Test_BufferSize doesn't seem to test anything. It only does an assertion.
15. The tests inside FB_TestStreamBuffer seem to depend on each other, which is not a good habit (https://medium.com/better-programming/13-tips-for-writing-useful-unit-tests-ca20706b5368, see point 8). Is it possible to make the tests be independent of each other?
16. Use same naming conventions as the rest of TcUnit/TcUnit-Verifier (for example, szFilename => PathFileName or pStrBuf => PointerToStringBuffer, and try to avoid names like "i : UDINT" altogether, Concat => Tc2_Standard.CONCAT(STR1 := '', STR2 := ''), sysdir => SysDir etc etc)
17. It's not necessary to initiate szFilename to STRING := 'testresults.xml' as this is set in the constructor anyway and is just confusing
18. Don't use pragma {attribute 'hide_all_locals'}
19. Rename FB_JUnitXmlPublisher -> FB_XUnitXmlLogger? (implements I_TestResultLogger) (same for the tests)
20. TestFileControl : FB_TestFileControl; is commented out in PRG_Test of TcUnit-Verifier?
21. End exporting of XML-file control the same way as ending of the TcUnit test results: "======================================" instead of "===================================="
22. Rename the default file name from testresults.xml to tcunit_xunit_testresults.xml?
23. I tested the resulting testresults.xml from running the TcUnit-Verifier against the following XSD: https://raw.githubusercontent.com/junit-team/junit5/master/platform-tests/src/test/resources/jenkins-junit.xsd in the following validator https://www.freeformatter.com/xml-validator-xsd.html and it failed.
24. Noticed that SysDir has been added as reference. Is this available in Tc 4020 as well?

 
 And some minor:
 - Start all variables/comments with uppercase
 - End comments with (* blabla *) instead of (* blabla*)
 - Is it possible to "BeautifY" the XML-output?

**Comment by Aliazzzz** [comment]
I will squash it when all changes are done

**Comment by dfreiberger** [comment]
@Aliazzzz  I am testing this out, and hoping to use it for a project. I just got it to work with Azure Pipelines to produce a nice report, and it worked great. Are there any issues remaining before it could be merged (besides the conflicts)? Is there anything I could help with?

**Comment by Aliazzzz** [comment]
Good to hear that you are satisfied with it!
I have not been able to write sufficient unit tests for it. If you would write some unit tests for the extension that would be great!

**Comment by sagatowski** [comment]
I'll make sure to go through the PR and update the "TODO"-list above, and put a mark in the checkbox if it's done so you can see what's left to do.

**Comment by sagatowski** [comment]
This is a duplicate of #91. See #91.

**Comment by sagatowski** [comment]
@Aliazzzz  & @dfreiberger . Look at #91. I've gone through the code and updated the "to-do" list. There are still some things that would be great if they were done. It's primarily adding tests to the C# verifier so that I can be sure that any future changes in the codebase doesn't break the unit testing framework. If this is done I'll merge the code into the main so it will be included in the TcUnit release 1.1.

**Comment by dfreiberger** [comment]
@sagatowski I have attempted to address some of the issues in your list, currently a part of PR https://github.com/Aliazzzz/TcUnit/pull/1

I will work on addressing more of the issues as time permits.

I believe I haven't caused any regressions in the TwinCAT project files as I was careful not to commit them (since I can only run the tests in a VM currently which requires different CPU settings), but let me know if you have any concerns.

**Pull request closed without merging**
